services:
  my-service-production:
    container_name: my-service-production
    build:
      context: .
      target: production
    ports:
      - "3001:3001"
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    build:
      context: .
      target: dev
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  momgodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.initiate().ok || rs.status().ok", "--quiet"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
